#LINUX COMMANDS: 

#COMPILATION:
gcc main.c encode.c decode.c

#CREATE OUTPUT FILE:
gcc main.c encode.c decode.c -o a.out

#ENCODING:
./a.out -e original.bmp secret.txt stego.bmp

#DECODING:
 ./a.out -d stego.bmp decode.txt
 
 #VIEW SECRET MESSAGE:
 cat secret.txt
